# Generated by Django 2.2 on 2019-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='by_request',
            field=models.BooleanField(default=False),
        ),
    ]
