# Generated by Django 2.2 on 2019-04-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('belt', '0002_event_by_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_trips', to='login.Person')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='belt.Event')),
            ],
        ),
    ]
