# Generated by Django 2.2 on 2019-04-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_user_name'),
        ('belt', '0003_eventrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_awarded', to='login.Person')),
                ('awarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_received', to='login.Person')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='belt.Event')),
            ],
        ),
    ]
