# Generated by Django 2.2 on 2019-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_earthpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthpoints',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
