# Generated by Django 2.2 on 2019-04-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_name',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
            preserve_default=False,
        ),
    ]
