# Generated by Django 2.2 on 2019-04-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
