# Generated by Django 2.2 on 2019-04-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190425_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
